{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a0a154d9-dd54-4590-a878-5aa0c4244e7f",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: huggingface_hub in /u/zongzhex/.local/lib/python3.9/site-packages (0.33.4)\n",
      "Requirement already satisfied: filelock in /sw/external/python/anaconda3/lib/python3.9/site-packages (from huggingface_hub) (3.9.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /u/zongzhex/.local/lib/python3.9/site-packages (from huggingface_hub) (2025.7.0)\n",
      "Requirement already satisfied: packaging>=20.9 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from huggingface_hub) (23.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from huggingface_hub) (5.4.1)\n",
      "Requirement already satisfied: requests in /sw/external/python/anaconda3/lib/python3.9/site-packages (from huggingface_hub) (2.31.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from huggingface_hub) (4.65.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /u/zongzhex/.local/lib/python3.9/site-packages (from huggingface_hub) (4.14.1)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /u/zongzhex/.local/lib/python3.9/site-packages (from huggingface_hub) (1.1.5)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from requests->huggingface_hub) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from requests->huggingface_hub) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from requests->huggingface_hub) (1.26.16)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /sw/external/python/anaconda3/lib/python3.9/site-packages (from requests->huggingface_hub) (2023.7.22)\n"
     ]
    }
   ],
   "source": [
    "!pip install huggingface_hub"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "144494fb-4e87-4414-891a-512e884b4c5f",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (352295474.py, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[4], line 2\u001b[0;36m\u001b[0m\n\u001b[0;31m    $export HF_TOKEN=\"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\"\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "from huggingface_hub import snapshot_download\n",
    "export HF_TOKEN=\"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\"\n",
    "snapshot_download(\n",
    "    repo_id=\"stabilityai/stable-diffusion-3-medium-diffusers\",\n",
    "    revision=\"ea42f8cef0f178587cf766dc8129abd379c90671\",\n",
    "    cache_dir=\"/projects/besp/BiosignalGen_zitao/\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "75b7f7d3-6df2-4830-877d-06894e172e9b",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "from sleepdataloader import SleepEpochDataset, ECG_Text_Dataset\n",
    "from config import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "90d769c0-ffe2-404b-8406-474d3482cc04",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading mimic-iv-ecg test dataset: total 771693 samples\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "TRAIN_EDF_COLS = [ECG]\n",
    "# dataset = SleepEpochDataset(\n",
    "#     epoch_df, patient_df, split=\"train\",\n",
    "#     train_edf_cols = TRAIN_EDF_COLS,\n",
    "#     target_cols=None,     # or None\n",
    "#     sample_rate=128,\n",
    "# )\n",
    "dataset = ECG_Text_Dataset(\n",
    "    split=\"test\",\n",
    "    dataset_dir=\"/projects/besp/shared_data/new_mimic/\",  \n",
    "    dataset_list=[\"mimic-iv-ecg\"],\n",
    "    use_cmsc=False,\n",
    "    use_rlm=False,\n",
    "    data_pct=1,\n",
    "    num_beats=1\n",
    ")\n",
    "loader = DataLoader(\n",
    "    dataset,\n",
    "    batch_size=16,\n",
    "    shuffle=False,\n",
    "    num_workers=4,\n",
    "    pin_memory=True,\n",
    "    drop_last=True\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e39fb648-6861-4ba7-91a9-3fd9c8564d54",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "Caught FileNotFoundError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py\", line 349, in _worker_loop\n    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/u/zongzhex/biogen_proj/biogen/mar_biogen/sleepdataloader.py\", line 266, in __getitem__\n    ecg = wfdb.rdsamp(row[\"path\"])[0].T              # (leads, T)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 2345, in rdsamp\n    record = rdrecord(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 2051, in rdrecord\n    record = rdheader(record_name, pn_dir=pn_dir, rd_segments=False)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 1855, in rdheader\n    with fsspec.open(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/core.py\", line 105, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/spec.py\", line 1338, in open\n    f = self._open(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 210, in _open\n    return LocalFileOpener(path, mode, fs=self, **kwargs)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 387, in __init__\n    self._open()\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 392, in _open\n    self.f = open(self.path, mode=self.mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/projects/besp/shared_data/new_mimic/mimic-iv-ecg/files/p1228/p12281109/s44199379/44199379.hea'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[7], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m data \u001b[38;5;129;01min\u001b[39;00m loader:\n\u001b[1;32m      2\u001b[0m     \u001b[38;5;28mprint\u001b[39m(data[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m0\u001b[39m]\u001b[38;5;241m.\u001b[39mshape)\n\u001b[1;32m      3\u001b[0m     \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "File \u001b[0;32m~/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/dataloader.py:734\u001b[0m, in \u001b[0;36m_BaseDataLoaderIter.__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    731\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sampler_iter \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    732\u001b[0m     \u001b[38;5;66;03m# TODO(https://github.com/pytorch/pytorch/issues/76750)\u001b[39;00m\n\u001b[1;32m    733\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_reset()  \u001b[38;5;66;03m# type: ignore[call-arg]\u001b[39;00m\n\u001b[0;32m--> 734\u001b[0m data \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_next_data\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    735\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m    736\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[1;32m    737\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_dataset_kind \u001b[38;5;241m==\u001b[39m _DatasetKind\u001b[38;5;241m.\u001b[39mIterable\n\u001b[1;32m    738\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    739\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_num_yielded \u001b[38;5;241m>\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_IterableDataset_len_called\n\u001b[1;32m    740\u001b[0m ):\n",
      "File \u001b[0;32m~/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1516\u001b[0m, in \u001b[0;36m_MultiProcessingDataLoaderIter._next_data\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1514\u001b[0m worker_id \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_task_info\u001b[38;5;241m.\u001b[39mpop(idx)[\u001b[38;5;241m0\u001b[39m]\n\u001b[1;32m   1515\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_rcvd_idx \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m-> 1516\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_process_data\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mworker_id\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1551\u001b[0m, in \u001b[0;36m_MultiProcessingDataLoaderIter._process_data\u001b[0;34m(self, data, worker_idx)\u001b[0m\n\u001b[1;32m   1549\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_try_put_index()\n\u001b[1;32m   1550\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(data, ExceptionWrapper):\n\u001b[0;32m-> 1551\u001b[0m     \u001b[43mdata\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mreraise\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1552\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m data\n",
      "File \u001b[0;32m~/.conda/envs/melp/lib/python3.10/site-packages/torch/_utils.py:769\u001b[0m, in \u001b[0;36mExceptionWrapper.reraise\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    765\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:\n\u001b[1;32m    766\u001b[0m     \u001b[38;5;66;03m# If the exception takes multiple arguments or otherwise can't\u001b[39;00m\n\u001b[1;32m    767\u001b[0m     \u001b[38;5;66;03m# be constructed, don't try to instantiate since we don't know how to\u001b[39;00m\n\u001b[1;32m    768\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(msg) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m--> 769\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m exception\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: Caught FileNotFoundError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py\", line 349, in _worker_loop\n    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File \"/u/zongzhex/biogen_proj/biogen/mar_biogen/sleepdataloader.py\", line 266, in __getitem__\n    ecg = wfdb.rdsamp(row[\"path\"])[0].T              # (leads, T)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 2345, in rdsamp\n    record = rdrecord(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 2051, in rdrecord\n    record = rdheader(record_name, pn_dir=pn_dir, rd_segments=False)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/wfdb/io/record.py\", line 1855, in rdheader\n    with fsspec.open(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/core.py\", line 105, in __enter__\n    f = self.fs.open(self.path, mode=mode)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/spec.py\", line 1338, in open\n    f = self._open(\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 210, in _open\n    return LocalFileOpener(path, mode, fs=self, **kwargs)\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 387, in __init__\n    self._open()\n  File \"/u/zongzhex/.conda/envs/melp/lib/python3.10/site-packages/fsspec/implementations/local.py\", line 392, in _open\n    self.f = open(self.path, mode=self.mode)\nFileNotFoundError: [Errno 2] No such file or directory: '/projects/besp/shared_data/new_mimic/mimic-iv-ecg/files/p1228/p12281109/s44199379/44199379.hea'\n"
     ]
    }
   ],
   "source": [
    "for data in loader:\n",
    "    print(data[0][0].shape)\n",
    "    break"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python melp",
   "language": "python",
   "name": "melp"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
